### ISSUE TITLE
Right-click - Start route here - then "paste"  ---> error

### ISSUE THREAD

**Issue by rgleason** [SaltyPaws/route_pi#13]
Right-click > Start route here -  the values go directly  into "Start of Route"
Right-click > Finish route here - the values go directly into "Finish of Route"
User confusion. if user then tries "Paste""  get an error.

![doublepaste](https://cloud.githubusercontent.com/assets/2363959/15991281/517e2990-307c-11e6-9570-67473e6881fd.jpg)
Don't know how to resolve this, just be able to paste or have a message?

**Comment by rgleason** [comment]
Checked copy functions from
Right-click > Drop Mark     Right-Click on Mark > Properties  
Then use "Copy" and paste to cell
Then use "Copy lat/long" and select "Paste" - there are several good prompts notifying that the format is changing to dec.deg.. and it seems to work.

Have tried with Units set to:
Dec.deg   --> when select "Copy lat/long" and then hit "Paste", two messages converting, then "Error: Cannot process coord input for >>49.533610  <<Converted as degree<< please ensure input is in decimal and remove symbols and letters." 

Dec.min  --> when select "Copy lat/long" and then hit "Paste", two messages converting and it works.

Dec-Sec-Min  --> when select "Copy lat/long" and then hit "Paste", two messages converting and it works.


When I do a "Copy" and then use  right-click in cell windows menu "Paste"  and then hit  "calculate" after using copy to copy all the lat/long pairs,   I get a number of conversion prompts and the values get changed to dec.degrees  and the calculation is done.

Deg-Min-Sec
all ok

**Comment by rgleason** [comment]
This appears to be fixed after some tests.

**Comment by SaltyPaws** [comment]
I can add this info to the mouseover text. E.g.

Use paste button only if the clipboard contains a coordinate pair. Right clicking with use "Start/finish route_pi here" will directly update the coordinates.

What do you think?

**Comment by rgleason** [comment]
Just thinking.... 
Some users will notice that if they Right-click and pick "Start route..." that the values are automatically entered into the Decimal Degree start lat/long.
Others won't, and will think they need to then click on "Paste"
This is when a message "These values have already been entered automatically by selecting "Start route..." could appear,   rather than the one I got showing above.
---
Looking again at what you wrote:
"Use paste button only if the clipboard contains a coordinate pair. Right clicking with use "Start/finish route_pi here" will directly update the coordinates."

Yes, this is better!  Thanks.

**Comment by SaltyPaws** [comment]
Done :)

For improvement suggestions: please use github rather than flyspray.

Kind regards,

Walbert

**Comment by rgleason** [comment]
Ok I'll try to remember to use githup rather than flyspray.
