### ISSUE TITLE
Start and Finish are same waypoint - Hit calc - should be a message "Start and finish are same"

### ISSUE THREAD

**Issue by rgleason** [SaltyPaws/route_pi#14]
There is a strange result in the cell when this condition occurs.

Should probably have a message "Start and Finish are the same"

**Comment by SaltyPaws** [comment]
Added :)

**Comment by SaltyPaws** [comment]
Hi Rick,

I believe the only thing outstanding is a fully fledged conversion function for coordinates. Do you think we can release the plugin as is, and add the conversion function to the next version (1.3)? Perhaps if we release some more issues will come to light, so I can also address them in the next issue.

Please accept my invite to the repository, so I can assign issues to you, so you can read them. I dont know of another way for me to open an issue and add you as participant.

**Comment by rgleason** [comment]
PS, Thanks for fixing this.

Yes, I think this is a good idea, to release and add the conversion function later with other items which come to light.

I will accept.  I do get messages from this git repos  route_pi and I usually read them all.
I did put a version compiled late this afternoon up on file thingie, but I see you did another commit 
 b268dac 14 minutes ago

I will remove that one on File Thingie that is outdated and build again tomorrow and upload, if it runs ok.

I think you can close this item now, if you like.

**Comment by SaltyPaws** [comment]
How do we get the updated plugin packages on the OpenCPN page? I have
attached the linux packages and .so file


Thanks for your help.

I will be on a trip for the next week, but thereafter I will look at your
suggestions.

Kind regards,

Walbert

**Comment by rgleason** [comment]
Pavel, 
Saltypaws would like to release an updared version of route_pi. Can you please help?See below.
ThanksRick

-------- Original message --------
