### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by mschiff** [SaltyPaws/route_pi#3]
Hi!

It would be very usefull to have tagged releases, so the source for a specific version of th eplugin can be downloaded. Please add a release/tag for your released versions. This makes packaging a lot easier. 

I'd like to package this plugin for Gentoo Linux and for that it requires a reliable specific download URL for the releases. 

Thanks in advance!

**Comment by SaltyPaws** [comment]
I am preparing the plugin for the next release. As soon as it is ready, I will tag the plugin.

**Comment by SaltyPaws** [comment]
Have you had any error messages with "The package is of bad quality" or such like, when trying to install the package in linux? Perhaps you could check out Issue #12 and let me know the best way to fix this? Thanks for your help!

**Comment by SaltyPaws** [comment]
Done, while you look at the package, I would really appreciate your help in fixing the Debian package quality issues.
