### ISSUE TITLE
obsolete source : would you update it please

### ISSUE THREAD

**Issue by filochard** [SaltyPaws/route_pi#5]
Hi
I saw you provide new version for Mac or Windows

I can't build your plugin with Linux 
(Cmakelist errors)
I discovered some pull requests allowing to build your plugin outside of the opencpn tree but they were not merged!

Do you use hidden or private sources to build your packages for Mac or Windows ?

**Comment by nohal** [comment]
No hidden source tree, the packages are built from my repo (the one from which the PRs are created)

**Comment by filochard** [comment]
Hi nohal
Actually this message was sent to SaltyPaws whose I used the master code
I discovered your fork (reading your pull request)
And I could now build route_pi (and SAR_pi) that I couldn't build with the source downloaded from 
https://github.com/SaltyPaws/route_pi (or https://github.com/SaltyPaws/SAR_pi)
I will now use :
https://github.com/nohal/route_pi (or https://github.com/nohal/SAR_pi)

**Comment by SaltyPaws** [comment]
Switch to the standard build system #4 commit has been implemented in the code. This should resolve this issue. Please let me know if this is not the case, and then I will reopen.
